-- Create a role (user) with limited (read-only) privileges
CREATE ROLE moose WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION CONNECTION LIMIT 64 ENCRYPTED PASSWORD 'AE0EE';
-- Create a role with full read/write privileges but not DB Admin privs
CREATE ROLE radio WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION CONNECTION LIMIT 64 ENCRYPTED PASSWORD 'aprsPropagation/AE0EE'

